In [1]:
import numpy as np

In [2]:
oneDarray = np.array([1,2,3,4,5])
print(oneDarray)

[1 2 3 4 5]


In [3]:
print(oneDarray.ndim)

1


In [4]:
twoDarray = np.array([[1,2,3],[4,5,6]])

In [5]:
print(twoDarray)

[[1 2 3]
 [4 5 6]]


In [6]:
twoDarray.ndim

2

In [7]:
threeDarray = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(threeDarray)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [8]:
print(threeDarray.ndim)

3


In [9]:
twoDarray = np.array([[1,2,3],[4,5,6]])
print(twoDarray)

[[1 2 3]
 [4 5 6]]


In [10]:
print(twoDarray[1])
print(twoDarray[1][2])


[4 5 6]
6


In [11]:
print(threeDarray)
print(threeDarray[0][1][1])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
5


In [12]:
print(twoDarray.shape)

(2, 3)


In [13]:
for i in twoDarray:
    print(i)

[1 2 3]
[4 5 6]


In [14]:
for i in twoDarray:
    for j in i:
        print(j)

1
2
3
4
5
6


In [15]:
for i in threeDarray:
    for j in i:
        for k in j:
            print(k)

1
2
3
4
5
6
7
8
9
10
11
12


In [16]:
zerosArray = np.zeros(10)
print(zerosArray)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [17]:
print(np.zeros((3,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [18]:
print(np.ones(10))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [19]:
oneArray = np.ones((10))
oneArray = oneArray.astype(int)
print(oneArray)

[1 1 1 1 1 1 1 1 1 1]


In [20]:
fullArray = np.full(10,5)
print(fullArray)

[5 5 5 5 5 5 5 5 5 5]


In [21]:
print(np.zeros(9).astype(int))

[0 0 0 0 0 0 0 0 0]


In [22]:
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


In [23]:
print(matrix + 2)

[[3 4 5]
 [6 7 8]]


In [24]:
print(matrix -2)

[[-1  0  1]
 [ 2  3  4]]


In [25]:
print(matrix * 2)

[[ 2  4  6]
 [ 8 10 12]]


In [26]:
twoDarray1 = np.array( [[3,4,5],[8,7,6]])
print(twoDarray1 * twoDarray)

[[ 3  8 15]
 [32 35 36]]


In [27]:
print(matrix /2)

[[0.5 1.  1.5]
 [2.  2.5 3. ]]


In [28]:
print(matrix // 2)

[[0 1 1]
 [2 2 3]]


In [29]:
print(matrix ** 2)

[[ 1  4  9]
 [16 25 36]]


In [30]:
print(matrix.T)

[[1 4]
 [2 5]
 [3 6]]


In [31]:
matrix1 = np.array([[1,2,3],[4,5,6]])
matrix2 = np.array([[7,8,9],[10,11,12]])
print(matrix + matrix2)

[[ 8 10 12]
 [14 16 18]]


In [32]:
print(matrix2 - matrix1)

[[6 6 6]
 [6 6 6]]


In [33]:
print(matrix1 * matrix2)

[[ 7 16 27]
 [40 55 72]]


In [34]:
print(matrix2 // matrix1)

[[7 4 3]
 [2 2 2]]


In [35]:
matrix1.ndim
print(matrix2.ndim)

2
